[package]
name = "freecam_bcrypt_proxy"
version = "0.1.0"
edition = "2021"

[lib]
name = "bcrypt"
crate-type = ['cdylib']

[dependencies]
rust_hooking_utils.workspace = true
freecam_rs = {path = "../freecam_rs"}
windows.workspace = true

[build-dependencies]
forward-dll.workspace = true
